version: '3.7'
services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    volumes:
      - ./mysql:/var/lib/mysql/
      - ./schema:/docker-entrypoint-initdb.d

    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass